name: Sync Notion to Website

on:
  schedule:
    - cron: '30 22 * * 1-5'  
  workflow_dispatch:  # Allows manual trigger
    inputs:
      dialog_date:
        description: 'Override dialog date (YYYY-MM-DD format)'
        required: false
        default: ''

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Install Notion client
        run: npm install @notionhq/client
        
      - name: Run blog sync script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: node sync.js
        
      - name: Run daily market sync script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DAILY_DATABASE_ID: ${{ secrets.NOTION_DAILY_DATABASE_ID }}
        run: node sync-daily.js
        
      - name: Run dialog sync script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_KEY: ${{ secrets.NOTION_TOKEN }}
          NOTION_DIALOG_DATABASE_ID: ${{ secrets.NOTION_DIALOG_DATABASE_ID }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DIALOG_DATABASE_ID }}
          DIALOG_JSON_PATH: './assets/js/dialog.json'
        run: |
          DATE_PARAM=""
          if [ -n "${{ github.event.inputs.dialog_date }}" ]; then
            DATE_PARAM="--date=${{ github.event.inputs.dialog_date }}"
          fi
          node update-dialog.js $DATE_PARAM
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Auto-sync from Notion" || echo "No changes to commit"
          git push
